### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'startswith' error after update to 1.0.4

### ISSUE THREAD

**Issue by leiendeckerlu** [bcbio/bcbio-nextgen#2018]
Hi there,

setting `svprioritize: cancer/civic` results in the following error:

> Traceback (most recent call last):
>   File "/bcbio/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/ipythontasks.py", line 50, in _setup_logging
>     yield config
>   File "/bcbio/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/ipythontasks.py", line 480, in organize_samples
>     return ipython.zip_args(apply(run_info.organize, *args))
>   File "/bcbio/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/run_info.py", line 70, in organize
>     item = add_reference_resources(item, remote_retriever)
>   File "/bcbio/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/run_info.py", line 183, in add_reference_resources
>     data = _fill_prioritization_targets(data)
>   File "/bcbio/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/run_info.py", line 267, in _fill_prioritization_targets
>     os.path.dirname(os.path.realpath(utils.which("simple_sv_annotation.py"))),
>   File "/bcbio/local/share/bcbio/anaconda/lib/python2.7/posixpath.py", line 375, in realpath
>     path, ok = _joinrealpath('', filename, {})
>   File "/bcbio/local/share/bcbio/anaconda/lib/python2.7/posixpath.py", line 381, in _joinrealpath
>     if isabs(rest):
>   File "/bcbio/local/share/bcbio/anaconda/lib/python2.7/posixpath.py", line 54, in isabs
>     return s.startswith('/')
> AttributeError: 'NoneType' object has no attribute 'startswith'

Solution for me: Remove svprioritize option.

The same error is occuring when running bwa:

> 
> [2017-07-24T08:49Z] compute-6-28: Aligning lane 1T with bwa aligner
> [2017-07-24T08:49Z] compute-6-15: Unexpected error
> Traceback (most recent call last):
>   File "/bcbio/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/ipythontasks.py", line 50, in _setup_logging
>     yield config
>   File "/bcbio/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/ipythontasks.py", line 205, in process_alignment
>     return ipython.zip_args(apply(sample.process_alignment, *args))
>   File "/bcbio/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/sample.py", line 116, in process_alignment
>     data = align_to_sort_bam(fastq1, fastq2, aligner, data)
>   File "/bcbio/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/alignment.py", line 65, in align_to_sort_bam
>     names, align_dir, data)
>   File "/bcbio/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/alignment.py", line 119, in _align_from_fastq
>     out = align_fn(fastq1, fastq2, align_ref, names, align_dir, data)
>   File "/bcbio/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/ngsalign/bwa.py", line 163, in align_pipe
>     names, rg_info, data)
>   File "/bcbio/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/ngsalign/bwa.py", line 172, in _align_mem
>     "%s | %s" % (_get_bwa_mem_cmd(data, out_file, ref_file, fastq_file, pair_file), tobam_cl))
>   File "/bcbio/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/ngsalign/bwa.py", line 67, in _get_bwa_mem_cmd
>     bwakit_dir = os.path.dirname(os.path.realpath(utils.which("run-bwamem")))
>   File "/bcbio/local/share/bcbio/anaconda/lib/python2.7/posixpath.py", line 375, in realpath
>     path, ok = _joinrealpath('', filename, {})
>   File "/bcbio/local/share/bcbio/anaconda/lib/python2.7/posixpath.py", line 381, in _joinrealpath
>     if isabs(rest):
>   File "/bcbio/local/share/bcbio/anaconda/lib/python2.7/posixpath.py", line 54, in isabs
>     return s.startswith('/')
> AttributeError: 'NoneType' object has no attribute 'startswith'

**Comment by leiendeckerlu** [comment]
An update on this: It seems that the newest bcbio version deletes files that are within /work/log/ipython/startup/ at some point during runs? That seems to cause the trouble for me, since I've a cluster specific config file there...

**Comment by chapmanb** [comment]
Sorry about the problem, the error message looks like you're missing tools in your path. If all of the bcbio tools are up to date, you need to ensure the `--tooldir` directory where they're located is present at the start of your `PATH`. Hope this resolves the issues for you.

**Comment by chapmanb** [comment]
Sorry, meant to also ask about the ipython setup. We don't purposely delete any directories as far as I remember, although I'm not sure about the behavior of ipython itself. If this is where you're setting the PATH I'm not totally sure what to suggest as I haven't tweaked ipython at this level myself. I'm happy to adjust anything inside bcbio to avoid this if we can identify where it's coming from.

**Comment by andreamarto** [comment]
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "offwhite.py", line 55, in run
    self.re = self.s.post(url, data=self.data, proxies=self.proxy)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/requests/sessions.py", line 555, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/requests/adapters.py", line 440, in send
    timeout=timeout
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/urllib3/connectionpool.py", line 595, in urlopen
    self._prepare_proxy(conn)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/urllib3/connectionpool.py", line 816, in _prepare_proxy
    conn.connect()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/urllib3/connection.py", line 284, in connect
    conn = self._new_conn()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/urllib3/connection.py", line 141, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/urllib3/util/connection.py", line 51, in create_connection
    if host.startswith('['):
AttributeError: 'NoneType' object has no attribute 'startswith'

**Comment by andreamarto** [comment]
can someone help me?

**Comment by roryk** [comment]
Hi Andrea-- it looks like you are running on OSX, which we don't support unfortunately. A lot of the third party tools don't work on OSX, see http://bcbio-nextgen.readthedocs.io/en/latest/contents/installation.html#installation for more information.
